# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: book_transaction.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'book_transaction.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x62ook_transaction.proto\x12\x18\x62ook_transaction_service\x1a\x1fgoogle/protobuf/timestamp.proto\"\xba\x01\n\x0f\x42ookTransaction\x12\x11\n\tbook_name\x18\x01 \x01(\t\x12\x19\n\x11is_book_available\x18\x02 \x01(\x08\x12\x13\n\x0bmember_name\x18\x03 \x01(\t\x12\x31\n\rborrowed_time\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x31\n\rreturned_time\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"K\n\x12TransactionRequest\x12\x35\n\x11transactions_from\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"V\n\x13TransactionResponse\x12?\n\x0ctransactions\x18\x01 \x03(\x0b\x32).book_transaction_service.BookTransaction2\x8f\x01\n\x16\x42ookTransactionService\x12u\n\x14ListBookTransactions\x12,.book_transaction_service.TransactionRequest\x1a-.book_transaction_service.TransactionResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'book_transaction_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BOOKTRANSACTION']._serialized_start=86
  _globals['_BOOKTRANSACTION']._serialized_end=272
  _globals['_TRANSACTIONREQUEST']._serialized_start=274
  _globals['_TRANSACTIONREQUEST']._serialized_end=349
  _globals['_TRANSACTIONRESPONSE']._serialized_start=351
  _globals['_TRANSACTIONRESPONSE']._serialized_end=437
  _globals['_BOOKTRANSACTIONSERVICE']._serialized_start=440
  _globals['_BOOKTRANSACTIONSERVICE']._serialized_end=583
# @@protoc_insertion_point(module_scope)
