/**
 * @fileoverview gRPC-Web generated client stub for book_service
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v6.31.1
// source: book.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js')
const proto = {};
proto.book_service = require('./book_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.book_service.BookServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'binary';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.book_service.BookServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'binary';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.book_service.CreateBookRequest,
 *   !proto.book_service.CreateBookResponse>}
 */
const methodDescriptor_BookService_CreateBook = new grpc.web.MethodDescriptor(
  '/book_service.BookService/CreateBook',
  grpc.web.MethodType.UNARY,
  proto.book_service.CreateBookRequest,
  proto.book_service.CreateBookResponse,
  /**
   * @param {!proto.book_service.CreateBookRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.book_service.CreateBookResponse.deserializeBinary
);


/**
 * @param {!proto.book_service.CreateBookRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.book_service.CreateBookResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.book_service.CreateBookResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.book_service.BookServiceClient.prototype.createBook =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/book_service.BookService/CreateBook',
      request,
      metadata || {},
      methodDescriptor_BookService_CreateBook,
      callback);
};


/**
 * @param {!proto.book_service.CreateBookRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.book_service.CreateBookResponse>}
 *     Promise that resolves to the response
 */
proto.book_service.BookServicePromiseClient.prototype.createBook =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/book_service.BookService/CreateBook',
      request,
      metadata || {},
      methodDescriptor_BookService_CreateBook);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.book_service.UpdateBookRequest,
 *   !proto.book_service.UpdateBookResponse>}
 */
const methodDescriptor_BookService_UpdateBook = new grpc.web.MethodDescriptor(
  '/book_service.BookService/UpdateBook',
  grpc.web.MethodType.UNARY,
  proto.book_service.UpdateBookRequest,
  proto.book_service.UpdateBookResponse,
  /**
   * @param {!proto.book_service.UpdateBookRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.book_service.UpdateBookResponse.deserializeBinary
);


/**
 * @param {!proto.book_service.UpdateBookRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.book_service.UpdateBookResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.book_service.UpdateBookResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.book_service.BookServiceClient.prototype.updateBook =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/book_service.BookService/UpdateBook',
      request,
      metadata || {},
      methodDescriptor_BookService_UpdateBook,
      callback);
};


/**
 * @param {!proto.book_service.UpdateBookRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.book_service.UpdateBookResponse>}
 *     Promise that resolves to the response
 */
proto.book_service.BookServicePromiseClient.prototype.updateBook =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/book_service.BookService/UpdateBook',
      request,
      metadata || {},
      methodDescriptor_BookService_UpdateBook);
};


module.exports = proto.book_service;

