# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: member.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'member.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cmember.proto\x12\x0emember_service\x1a\x1fgoogle/protobuf/timestamp.proto\"b\n\x13\x43reateMemberRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05phone\x18\x02 \x01(\t\x12.\n\ncreated_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"1\n\x14\x43reateMemberResponse\x12\x19\n\x11is_member_created\x18\x01 \x01(\x08\"n\n\x13UpdateMemberRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05phone\x18\x03 \x01(\t\x12.\n\nupdated_at\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"1\n\x14UpdateMemberResponse\x12\x19\n\x11is_member_updated\x18\x01 \x01(\x08\x32\xc9\x01\n\rMemberService\x12[\n\x0c\x43reateMember\x12#.member_service.CreateMemberRequest\x1a$.member_service.CreateMemberResponse\"\x00\x12[\n\x0cUpdateMember\x12#.member_service.UpdateMemberRequest\x1a$.member_service.UpdateMemberResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'member_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATEMEMBERREQUEST']._serialized_start=65
  _globals['_CREATEMEMBERREQUEST']._serialized_end=163
  _globals['_CREATEMEMBERRESPONSE']._serialized_start=165
  _globals['_CREATEMEMBERRESPONSE']._serialized_end=214
  _globals['_UPDATEMEMBERREQUEST']._serialized_start=216
  _globals['_UPDATEMEMBERREQUEST']._serialized_end=326
  _globals['_UPDATEMEMBERRESPONSE']._serialized_start=328
  _globals['_UPDATEMEMBERRESPONSE']._serialized_end=377
  _globals['_MEMBERSERVICE']._serialized_start=380
  _globals['_MEMBERSERVICE']._serialized_end=581
# @@protoc_insertion_point(module_scope)
