# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: book.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'book.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nbook.proto\x12\x0c\x62ook_service\x1a\x1fgoogle/protobuf/timestamp.proto\"\xac\x01\n\x11\x43reateBookRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x02 \x01(\t\x12\x13\n\x0bmember_name\x18\x03 \x01(\t\x12\x31\n\rborrowed_time\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x31\n\rreturned_time\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"-\n\x12\x43reateBookResponse\x12\x17\n\x0fis_book_created\x18\x01 \x01(\x08\"\x1f\n\x11UpdateBookRequest\x12\n\n\x02id\x18\x01 \x01(\t\"-\n\x12UpdateBookResponse\x12\x17\n\x0fis_book_updated\x18\x01 \x01(\x08\x32\xb3\x01\n\x0b\x42ookService\x12Q\n\nCreateBook\x12\x1f.book_service.CreateBookRequest\x1a .book_service.CreateBookResponse\"\x00\x12Q\n\nUpdateBook\x12\x1f.book_service.UpdateBookRequest\x1a .book_service.UpdateBookResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'book_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATEBOOKREQUEST']._serialized_start=62
  _globals['_CREATEBOOKREQUEST']._serialized_end=234
  _globals['_CREATEBOOKRESPONSE']._serialized_start=236
  _globals['_CREATEBOOKRESPONSE']._serialized_end=281
  _globals['_UPDATEBOOKREQUEST']._serialized_start=283
  _globals['_UPDATEBOOKREQUEST']._serialized_end=314
  _globals['_UPDATEBOOKRESPONSE']._serialized_start=316
  _globals['_UPDATEBOOKRESPONSE']._serialized_end=361
  _globals['_BOOKSERVICE']._serialized_start=364
  _globals['_BOOKSERVICE']._serialized_end=543
# @@protoc_insertion_point(module_scope)
