# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from book.proto import book_pb2 as book_dot_proto_dot_book__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in book/proto/book_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BookServiceStub(object):
    """The Book service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateBook = channel.unary_unary(
                '/book_service.BookService/CreateBook',
                request_serializer=book_dot_proto_dot_book__pb2.CreateBookRequest.SerializeToString,
                response_deserializer=book_dot_proto_dot_book__pb2.CreateBookResponse.FromString,
                _registered_method=True)
        self.UpdateBook = channel.unary_unary(
                '/book_service.BookService/UpdateBook',
                request_serializer=book_dot_proto_dot_book__pb2.UpdateBookRequest.SerializeToString,
                response_deserializer=book_dot_proto_dot_book__pb2.UpdateBookResponse.FromString,
                _registered_method=True)


class BookServiceServicer(object):
    """The Book service definition.
    """

    def CreateBook(self, request, context):
        """A BookService RPC that takes a request and returns data.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateBook(self, request, context):
        """A UpdateBook RPC that takes a request and returns data.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BookServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateBook': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateBook,
                    request_deserializer=book_dot_proto_dot_book__pb2.CreateBookRequest.FromString,
                    response_serializer=book_dot_proto_dot_book__pb2.CreateBookResponse.SerializeToString,
            ),
            'UpdateBook': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateBook,
                    request_deserializer=book_dot_proto_dot_book__pb2.UpdateBookRequest.FromString,
                    response_serializer=book_dot_proto_dot_book__pb2.UpdateBookResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'book_service.BookService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('book_service.BookService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BookService(object):
    """The Book service definition.
    """

    @staticmethod
    def CreateBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/book_service.BookService/CreateBook',
            book_dot_proto_dot_book__pb2.CreateBookRequest.SerializeToString,
            book_dot_proto_dot_book__pb2.CreateBookResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/book_service.BookService/UpdateBook',
            book_dot_proto_dot_book__pb2.UpdateBookRequest.SerializeToString,
            book_dot_proto_dot_book__pb2.UpdateBookResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
