/**
 * @fileoverview gRPC-Web generated client stub for member_service
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v6.31.1
// source: member.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js')
const proto = {};
proto.member_service = require('./member_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.member_service.MemberServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'binary';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.member_service.MemberServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'binary';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.member_service.CreateMemberRequest,
 *   !proto.member_service.CreateMemberResponse>}
 */
const methodDescriptor_MemberService_CreateMember = new grpc.web.MethodDescriptor(
  '/member_service.MemberService/CreateMember',
  grpc.web.MethodType.UNARY,
  proto.member_service.CreateMemberRequest,
  proto.member_service.CreateMemberResponse,
  /**
   * @param {!proto.member_service.CreateMemberRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.member_service.CreateMemberResponse.deserializeBinary
);


/**
 * @param {!proto.member_service.CreateMemberRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.member_service.CreateMemberResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.member_service.CreateMemberResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.member_service.MemberServiceClient.prototype.createMember =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/member_service.MemberService/CreateMember',
      request,
      metadata || {},
      methodDescriptor_MemberService_CreateMember,
      callback);
};


/**
 * @param {!proto.member_service.CreateMemberRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.member_service.CreateMemberResponse>}
 *     Promise that resolves to the response
 */
proto.member_service.MemberServicePromiseClient.prototype.createMember =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/member_service.MemberService/CreateMember',
      request,
      metadata || {},
      methodDescriptor_MemberService_CreateMember);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.member_service.UpdateMemberRequest,
 *   !proto.member_service.UpdateMemberResponse>}
 */
const methodDescriptor_MemberService_UpdateMember = new grpc.web.MethodDescriptor(
  '/member_service.MemberService/UpdateMember',
  grpc.web.MethodType.UNARY,
  proto.member_service.UpdateMemberRequest,
  proto.member_service.UpdateMemberResponse,
  /**
   * @param {!proto.member_service.UpdateMemberRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.member_service.UpdateMemberResponse.deserializeBinary
);


/**
 * @param {!proto.member_service.UpdateMemberRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.member_service.UpdateMemberResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.member_service.UpdateMemberResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.member_service.MemberServiceClient.prototype.updateMember =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/member_service.MemberService/UpdateMember',
      request,
      metadata || {},
      methodDescriptor_MemberService_UpdateMember,
      callback);
};


/**
 * @param {!proto.member_service.UpdateMemberRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.member_service.UpdateMemberResponse>}
 *     Promise that resolves to the response
 */
proto.member_service.MemberServicePromiseClient.prototype.updateMember =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/member_service.MemberService/UpdateMember',
      request,
      metadata || {},
      methodDescriptor_MemberService_UpdateMember);
};


module.exports = proto.member_service;

