/**
 * @fileoverview gRPC-Web generated client stub for book_transaction_service
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v6.31.1
// source: book_transaction.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js')
const proto = {};
proto.book_transaction_service = require('./book_transaction_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.book_transaction_service.BookTransactionServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'binary';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.book_transaction_service.BookTransactionServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'binary';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.book_transaction_service.TransactionRequest,
 *   !proto.book_transaction_service.TransactionResponse>}
 */
const methodDescriptor_BookTransactionService_ListBookTransactions = new grpc.web.MethodDescriptor(
  '/book_transaction_service.BookTransactionService/ListBookTransactions',
  grpc.web.MethodType.UNARY,
  proto.book_transaction_service.TransactionRequest,
  proto.book_transaction_service.TransactionResponse,
  /**
   * @param {!proto.book_transaction_service.TransactionRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.book_transaction_service.TransactionResponse.deserializeBinary
);


/**
 * @param {!proto.book_transaction_service.TransactionRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.book_transaction_service.TransactionResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.book_transaction_service.TransactionResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.book_transaction_service.BookTransactionServiceClient.prototype.listBookTransactions =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/book_transaction_service.BookTransactionService/ListBookTransactions',
      request,
      metadata || {},
      methodDescriptor_BookTransactionService_ListBookTransactions,
      callback);
};


/**
 * @param {!proto.book_transaction_service.TransactionRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.book_transaction_service.TransactionResponse>}
 *     Promise that resolves to the response
 */
proto.book_transaction_service.BookTransactionServicePromiseClient.prototype.listBookTransactions =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/book_transaction_service.BookTransactionService/ListBookTransactions',
      request,
      metadata || {},
      methodDescriptor_BookTransactionService_ListBookTransactions);
};


module.exports = proto.book_transaction_service;

