// source: book_transaction.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
goog.exportSymbol('proto.book_transaction_service.BookTransaction', null, global);
goog.exportSymbol('proto.book_transaction_service.TransactionRequest', null, global);
goog.exportSymbol('proto.book_transaction_service.TransactionResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.book_transaction_service.BookTransaction = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.book_transaction_service.BookTransaction, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.book_transaction_service.BookTransaction.displayName = 'proto.book_transaction_service.BookTransaction';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.book_transaction_service.TransactionRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.book_transaction_service.TransactionRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.book_transaction_service.TransactionRequest.displayName = 'proto.book_transaction_service.TransactionRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.book_transaction_service.TransactionResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.book_transaction_service.TransactionResponse.repeatedFields_, null);
};
goog.inherits(proto.book_transaction_service.TransactionResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.book_transaction_service.TransactionResponse.displayName = 'proto.book_transaction_service.TransactionResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.book_transaction_service.BookTransaction.prototype.toObject = function(opt_includeInstance) {
  return proto.book_transaction_service.BookTransaction.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.book_transaction_service.BookTransaction} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.book_transaction_service.BookTransaction.toObject = function(includeInstance, msg) {
  var f, obj = {
bookName: jspb.Message.getFieldWithDefault(msg, 1, ""),
isBookAvailable: jspb.Message.getBooleanFieldWithDefault(msg, 2, false),
memberName: jspb.Message.getFieldWithDefault(msg, 3, ""),
borrowedTime: (f = msg.getBorrowedTime()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
returnedTime: (f = msg.getReturnedTime()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.book_transaction_service.BookTransaction}
 */
proto.book_transaction_service.BookTransaction.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.book_transaction_service.BookTransaction;
  return proto.book_transaction_service.BookTransaction.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.book_transaction_service.BookTransaction} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.book_transaction_service.BookTransaction}
 */
proto.book_transaction_service.BookTransaction.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setBookName(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIsBookAvailable(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setMemberName(value);
      break;
    case 4:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setBorrowedTime(value);
      break;
    case 5:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setReturnedTime(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.book_transaction_service.BookTransaction.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.book_transaction_service.BookTransaction.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.book_transaction_service.BookTransaction} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.book_transaction_service.BookTransaction.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getBookName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getIsBookAvailable();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
  f = message.getMemberName();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getBorrowedTime();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getReturnedTime();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
};


/**
 * optional string book_name = 1;
 * @return {string}
 */
proto.book_transaction_service.BookTransaction.prototype.getBookName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.book_transaction_service.BookTransaction} returns this
 */
proto.book_transaction_service.BookTransaction.prototype.setBookName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional bool is_book_available = 2;
 * @return {boolean}
 */
proto.book_transaction_service.BookTransaction.prototype.getIsBookAvailable = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 2, false));
};


/**
 * @param {boolean} value
 * @return {!proto.book_transaction_service.BookTransaction} returns this
 */
proto.book_transaction_service.BookTransaction.prototype.setIsBookAvailable = function(value) {
  return jspb.Message.setProto3BooleanField(this, 2, value);
};


/**
 * optional string member_name = 3;
 * @return {string}
 */
proto.book_transaction_service.BookTransaction.prototype.getMemberName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.book_transaction_service.BookTransaction} returns this
 */
proto.book_transaction_service.BookTransaction.prototype.setMemberName = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional google.protobuf.Timestamp borrowed_time = 4;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.book_transaction_service.BookTransaction.prototype.getBorrowedTime = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 4));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.book_transaction_service.BookTransaction} returns this
*/
proto.book_transaction_service.BookTransaction.prototype.setBorrowedTime = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.book_transaction_service.BookTransaction} returns this
 */
proto.book_transaction_service.BookTransaction.prototype.clearBorrowedTime = function() {
  return this.setBorrowedTime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.book_transaction_service.BookTransaction.prototype.hasBorrowedTime = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional google.protobuf.Timestamp returned_time = 5;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.book_transaction_service.BookTransaction.prototype.getReturnedTime = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 5));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.book_transaction_service.BookTransaction} returns this
*/
proto.book_transaction_service.BookTransaction.prototype.setReturnedTime = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.book_transaction_service.BookTransaction} returns this
 */
proto.book_transaction_service.BookTransaction.prototype.clearReturnedTime = function() {
  return this.setReturnedTime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.book_transaction_service.BookTransaction.prototype.hasReturnedTime = function() {
  return jspb.Message.getField(this, 5) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.book_transaction_service.TransactionRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.book_transaction_service.TransactionRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.book_transaction_service.TransactionRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.book_transaction_service.TransactionRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
transactionsFrom: (f = msg.getTransactionsFrom()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.book_transaction_service.TransactionRequest}
 */
proto.book_transaction_service.TransactionRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.book_transaction_service.TransactionRequest;
  return proto.book_transaction_service.TransactionRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.book_transaction_service.TransactionRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.book_transaction_service.TransactionRequest}
 */
proto.book_transaction_service.TransactionRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setTransactionsFrom(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.book_transaction_service.TransactionRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.book_transaction_service.TransactionRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.book_transaction_service.TransactionRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.book_transaction_service.TransactionRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTransactionsFrom();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
};


/**
 * optional google.protobuf.Timestamp transactions_from = 1;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.book_transaction_service.TransactionRequest.prototype.getTransactionsFrom = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 1));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.book_transaction_service.TransactionRequest} returns this
*/
proto.book_transaction_service.TransactionRequest.prototype.setTransactionsFrom = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.book_transaction_service.TransactionRequest} returns this
 */
proto.book_transaction_service.TransactionRequest.prototype.clearTransactionsFrom = function() {
  return this.setTransactionsFrom(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.book_transaction_service.TransactionRequest.prototype.hasTransactionsFrom = function() {
  return jspb.Message.getField(this, 1) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.book_transaction_service.TransactionResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.book_transaction_service.TransactionResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.book_transaction_service.TransactionResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.book_transaction_service.TransactionResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.book_transaction_service.TransactionResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
transactionsList: jspb.Message.toObjectList(msg.getTransactionsList(),
    proto.book_transaction_service.BookTransaction.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.book_transaction_service.TransactionResponse}
 */
proto.book_transaction_service.TransactionResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.book_transaction_service.TransactionResponse;
  return proto.book_transaction_service.TransactionResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.book_transaction_service.TransactionResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.book_transaction_service.TransactionResponse}
 */
proto.book_transaction_service.TransactionResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.book_transaction_service.BookTransaction;
      reader.readMessage(value,proto.book_transaction_service.BookTransaction.deserializeBinaryFromReader);
      msg.addTransactions(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.book_transaction_service.TransactionResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.book_transaction_service.TransactionResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.book_transaction_service.TransactionResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.book_transaction_service.TransactionResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTransactionsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.book_transaction_service.BookTransaction.serializeBinaryToWriter
    );
  }
};


/**
 * repeated BookTransaction transactions = 1;
 * @return {!Array<!proto.book_transaction_service.BookTransaction>}
 */
proto.book_transaction_service.TransactionResponse.prototype.getTransactionsList = function() {
  return /** @type{!Array<!proto.book_transaction_service.BookTransaction>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.book_transaction_service.BookTransaction, 1));
};


/**
 * @param {!Array<!proto.book_transaction_service.BookTransaction>} value
 * @return {!proto.book_transaction_service.TransactionResponse} returns this
*/
proto.book_transaction_service.TransactionResponse.prototype.setTransactionsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.book_transaction_service.BookTransaction=} opt_value
 * @param {number=} opt_index
 * @return {!proto.book_transaction_service.BookTransaction}
 */
proto.book_transaction_service.TransactionResponse.prototype.addTransactions = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.book_transaction_service.BookTransaction, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.book_transaction_service.TransactionResponse} returns this
 */
proto.book_transaction_service.TransactionResponse.prototype.clearTransactionsList = function() {
  return this.setTransactionsList([]);
};


goog.object.extend(exports, proto.book_transaction_service);
