# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import book_transaction_pb2 as book__transaction__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in book_transaction_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BookTransactionServiceStub(object):
    """The BookTransaction service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListBookTransactions = channel.unary_unary(
                '/book_transaction_service.BookTransactionService/ListBookTransactions',
                request_serializer=book__transaction__pb2.TransactionRequest.SerializeToString,
                response_deserializer=book__transaction__pb2.TransactionResponse.FromString,
                _registered_method=True)


class BookTransactionServiceServicer(object):
    """The BookTransaction service definition.
    """

    def ListBookTransactions(self, request, context):
        """A ListBookTransactions RPC that takes a TransactionRequest and returns TransactionResponse.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BookTransactionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListBookTransactions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBookTransactions,
                    request_deserializer=book__transaction__pb2.TransactionRequest.FromString,
                    response_serializer=book__transaction__pb2.TransactionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'book_transaction_service.BookTransactionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('book_transaction_service.BookTransactionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BookTransactionService(object):
    """The BookTransaction service definition.
    """

    @staticmethod
    def ListBookTransactions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/book_transaction_service.BookTransactionService/ListBookTransactions',
            book__transaction__pb2.TransactionRequest.SerializeToString,
            book__transaction__pb2.TransactionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
